variables:
  sln: progaudi.buffers.sln
  tests: tests/progaudi.buffers.tests/progaudi.buffers.tests.csproj

resources:
  repositories:
    - repository: templates
      type: github
      name: progaudi/azure-pipelines
      endpoint: progaudi

jobs:
- template: library/nuget.yml@templates
