variables:
  sln: progaudi.buffers.sln
  tests: tests/progaudi.buffers.tests/progaudi.buffers.tests.csproj

jobs:
- job: macOs
  pool:
    name: Hosted macOS
  steps:
    - template: .azure/install.yml
    - template: .azure/tests.yml

- job: linux
  pool:
    name: Hosted Ubuntu 1604
  steps:
    - template: .azure/install.yml
    - template: .azure/tests.yml

- job: win
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure/install.yml
    - template: .azure/tests.yml

- job: publish
  dependsOn:
  - macOs
  - linux
  - win
  pool:
    name: Hosted VS2017
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
    - template: .azure/install.yml

    - task: DownloadSecureFile@1
      inputs:
        secureFile: progaudi.snk

    - task: PowerShell@2
      displayName: pack nuget package
      inputs:
        targetType: inline
        script: |
            $version = $(git describe --tags | %{$_ -replace '-([^g])', '.$1'})
            dotnet pack -v minimal -c Release /property:SignAssembly=true /property:AssemblyOriginatorKeyFile=$(Agent.TempDirectory)\progaudi.snk /property:Version=$version /property:PackageOutputPath=$(Build.ArtifactStagingDirectory)

    - task: NuGetCommand@2
      displayName: push nuget packages
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: api.nuget.org

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: .nupkgs
